#!/usr/bin/env perl

use warnings;
use strict;
use feature 'say';

my $output_template = <<END;
{
  url = "URL";
  sha256 = "SHA256";
}
END

if ($#ARGV < 0) {
  say "I need the url you want to prefetch.";
  exit 1;
}

my $url = $ARGV[0];

my $result = `nix-prefetch-url $url`;
chomp($result);

if ($! != 0) {
  say "Could not successfully run nix-prefetch-url on $url";
  exit 1;
}

my $output = $output_template;
$output =~ s/URL/$url/;
$output =~ s/SHA256/$result/;

print $output;
